devs = [10 10 1e-5 1e-5 1 1 1e-6 1e-6]';
video_processing_multitarget(2, '..\sample_videos\Vid_J_person_floor.avi', ...
    cellstr(['..\gt\bobot\Vid_Ja_person_floor_left.txt '; '..\gt\bobot\Vid_Jb_person_floor_right.txt']), ...
    'results\vidJ.txt', 400, 8, 'bobot', devs, 'vidJ_frames');
